# Generated by Django 4.2.6 on 2023-10-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='viewed',
        ),
    ]
