# Generated by Django 4.2.6 on 2023-10-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_remove_activity_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
