# Generated by Django 4.2.5 on 2023-11-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
