# Generated by Django 4.2.4 on 2023-10-03 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_rename_name_role_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('power', models.DecimalField(decimal_places=5, max_digits=5)),
                ('port_type', models.CharField(max_length=20)),
                ('amp', models.DecimalField(decimal_places=5, max_digits=5)),
                ('warranty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('number_of_stars', models.IntegerField()),
                ('number_of_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.address', verbose_name='location')),
                ('charer_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charger.chargertype', verbose_name='charger_type')),
                ('renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
