# Generated by Django 4.2.4 on 2023-10-04 00:55

from django.db import migrations, models
import django.db.models.deletion
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('image', models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='evcharger-bucket'), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charger.chargerimage'),
        ),
    ]
