# Generated by Django 4.2.4 on 2023-10-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0002_chargerimage_alter_chargertype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargertype',
            name='amp',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='power',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
