# Generated by Django 4.2.4 on 2023-10-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0003_alter_chargertype_amp_alter_chargertype_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargertype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
