# Generated by Django 4.2.4 on 2023-10-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0004_alter_chargertype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charger',
            old_name='charer_type',
            new_name='charger_type',
        ),
    ]
