# Generated by Django 4.2.4 on 2023-10-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0006_alter_charger_charger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargertype',
            name='amp',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='port_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='power',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
