# Generated by Django 4.2.4 on 2023-10-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0007_alter_chargertype_amp_alter_chargertype_port_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargertype',
            name='warranty',
            field=models.IntegerField(null=True),
        ),
    ]
