# Generated by Django 4.2.6 on 2023-10-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0008_alter_chargertype_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='charger_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='charger.chargertype', verbose_name='charger_type'),
        ),
    ]
