# Generated by Django 4.2.6 on 2023-10-18 03:31

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ("charger", "0009_alter_charger_charger_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargerimage",
            name="image",
            field=models.ImageField(
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="evcharger-bucket-eren"
                ),
                upload_to="",
            ),
        ),
    ]
