# Generated by Django 4.2.6 on 2023-10-19 16:28

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0010_alter_chargerimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chargerimage',
            name='image',
            field=models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='evcharger-bucket'), upload_to=''),
        ),
    ]
