# Generated by Django 4.2.6 on 2023-10-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0011_charger_hourly_rate_alter_chargerimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
