# Generated by Django 4.2.6 on 2023-10-26 23:33

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0012_charger_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargerimage',
            name='image',
            field=models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='evcharger-buckets'), upload_to=''),
        ),
    ]
