# Generated by Django 4.2.6 on 2023-10-27 01:16

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0013_alter_chargerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargerimage',
            name='image',
            field=models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='evcharger-bucket'), upload_to=''),
        ),
    ]
