# Generated by Django 4.2.6 on 2023-10-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0014_alter_chargerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='port_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
