# Generated by Django 4.2.4 on 2023-10-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role',
        ),
    ]
