# Generated by Django 4.2.4 on 2023-10-03 23:45

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='evcharger-bucket'), upload_to=''),
        ),
    ]
