# Generated by Django 4.2.4 on 2023-10-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=50),
        ),
    ]
